bundler_args: --without development
before_script:
  - mysql -e 'CREATE DATABASE content_planner_test;'
before_install:
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake spec
rvm:
  - 2.1.2
branches:
  except:
    - release
    - /^release_[0-9]+$/
notifications:
  email: false
